# Generated by Django 3.1.1 on 2021-03-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipoCuenta', models.IntegerField(choices=[(0, 'Ahorros'), (1, 'Corriente')], default=0)),
                ('numeroCuenta', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(0, 'Activa'), (1, 'Inactica')], default=0)),
                ('saldo', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
